@startuml domainmodel
    left to right direction
    skinparam classAttributeIconSize 0

    abstract class Usuario {
        +nome : str
        +telefone : str
        +partidas : array[Partida]
    }

    class Jogador {
        +localização : str
        +posição : str
        +encontrarPartidas()
        +entrarPartida()
        +avaliarJogador()
    }

    class Organizador {
        +criarPartida()
        +cancelarPartida()
        +gerenciarjogadores()
    }

    class Partida {
        +localização : str
        +horário : DateTime
        +status : bool
        +jogadores : array[Jogador]
        +organizador : Organizador
        +addJogador()
        +removerJogador()
        +getJogadores()
    }

    Organizador --|> Usuario
    Jogador --|> Usuario
    Jogador "*" --* "*" Partida : joga >
    Organizador "1" -- "*" Partida : organiza >
    Organizador "*" -- "*" Jogador : gerencia >
@enduml
